# Generated by Django 4.0.5 on 2022-06-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("description", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BR", "Breakfast"),
                            ("LU", "Lunch"),
                            ("DI", "Dinner"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
